apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "22"
    field.cattle.io/creatorId: user-9l7cm
  creationTimestamp: "2021-04-30T12:46:20Z"
  generation: 27
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-onsite360-dev1-go-onsite-alert
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
              f:field.cattle.io/ports: {}
            f:labels:
              .: {}
              f:app: {}
              f:version: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"go-onsite-alert"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/go/config"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"registry-dkr-pvcp-intra"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"config"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                  f:optional: {}
                f:name: {}
    manager: rancher
    operation: Update
    time: "2021-07-19T07:51:07Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-09-06T13:23:29Z"
  name: go-onsite-alert
  namespace: onsite360-dev1
  resourceVersion: "40369859"
  uid: 1e4051e3-cd6b-43b3-aa7b-931227dabb96
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-onsite360-dev1-go-onsite-alert
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-08-31T15:07:36Z"
        field.cattle.io/ports: '[[{"containerPort":8000,"dnsName":"go-onsite-alert","hostPort":0,"kind":"ClusterIP","name":"go8000","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        app: onsite360-dev
        version: v1
        workload.user.cattle.io/workloadselector: deployment-onsite360-dev1-go-onsite-alert
    spec:
      containers:
      - image: registry-dkr.pvcp.intra:5000/pda/go-onsite-alert:develop-38fc7598
        imagePullPolicy: Always
        name: go-onsite-alert
        ports:
        - containerPort: 8000
          name: go8000
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /go/config
          name: config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-dkr-pvcp-intra
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: go-onsite-alert-config
          optional: false
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-22T08:09:45Z"
    lastUpdateTime: "2021-07-22T08:09:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-30T12:46:20Z"
    lastUpdateTime: "2021-09-06T13:23:29Z"
    message: ReplicaSet "go-onsite-alert-5dc6b586d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
